package exceptions.task_6_2;

public class Main {
}
